apiVersion: v1
kind: Service
metadata:
  name: {{ include "bank-insurance-app.fullname" . }}
  labels:
    app: {{ include "bank-insurance-app.name" . }}
spec:
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
  selector:
    app: {{ include "bank-insurance-app.name" . }}
